### ISSUE TITLE
Question after installing

### ISSUE THREAD

**Issue by dgleba** [laravella/laravella#26]
After installing, when I go to localhost, I get the following error message.

Can you help?

~=-=-=-=-=-=~ 

This webpage has a redirect loop

Reload  Less
The webpage at http://localhost/login has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer.
Learn more about this problem.
Error code: ERR_TOO_MANY_REDIRECTS

~=-=-=-=-=-=~

**Comment by laravella** [comment]
Please download the latest laravella project (not just a composer update) because the root routes.php has changed to fix this.  I have also made changes to the AccountController.

Make sure localhost/login redirects to localhost/account/login , or try using the latter link from the start.

Regards
Victor

**Comment by dgleba** [comment]
This issue is resolved.
